### ISSUE TITLE
Error in visualizing/saving NKSR mesh

### ISSUE THREAD

**Issue by minar09** [heiwang1997/pycg#1]
Hi, getting this error from pycg when trying to visualize/save NKSR mesh. 

`AttributeError: 'NoneType' object has no attribute 'convert_from_pinhole_camera_parameters'`

Installed the full pycg with the command: `pip install -U python-pycg[full] -f https://pycg.s3.ap-northeast-1.amazonaws.com/packages/index.html`

**Comment by heiwang1997** [comment]
Hi could you try disabling the visualization (i.e. remove `show_3d`) and just save the mesh? Maybe you are using a remote server and don't have X11 access.

**Comment by minar09** [comment]
You are right, saving mesh is working. Thank you for your response and the splendid work.
